name: 'Podcast Generator'
author: 'DouglasAmarelo'
description: 'Generates a feed for a podcast from YAML file - LinkedinLearning Course'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'git-branch'
  color: '#d0d'
inputs:
  email:
    description: "The commiter's email adress"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The commiter's name"
    required: true
    default: ${{ github.actor }}
